### ISSUE TITLE
Class names order

### ISSUE THREAD

**Issue by Riron** [LuccaSA/lucca-icons#1]
For icons, having to order the class names is too restrictive.

`<i class="lui icon south chevron></i>` => Works
`<i class="lui icon chevron south></i>` => Does not work
`<i class="lui icon south trololol chevron></i>` => Does not work

Can you fix it ?

**Comment by lucienbertin** [comment]
Well, if think we wont fix it, it being a design decision and all.

you can see it in the [release notes](https://github.com/LuccaSA/lucca-icons/releases/tag/1.1.0) associated with version 1.1, section "Breaking changes"

---

in a more broad way, it allows us more freedom to make the framework evolve. The all idea of lucca-ui css framework is to be semantical. It provides `elements` (button, menu, table) and adjectives (small, primary, ...). for it to work well sometimes you have to enforce the class order, for example you might want a div `left aligned` but also `right pulled`. If you enforce class name order you can have this div, if you don't enforce it it will just not work properly

``` html
<div class="lui left aligned right pulled"></div>`
```

When you apply that to lucca-icons you can understand the approach. icons `user`, `add user`, `remove user` and `to user` are very much alike. `user` is the `element` and `add`, `remove` and `to` are his supported adjectives. it's the same for `chevron`

also if we want to add some image transformation in the future, enforcing name order will allow us to support more stuff like
- `flipped` + `horizontally` or `vertically`
- `add effect` + `sepia` or some other stuff

you see that if we add these kind of features in the future we dont want to have to make exceptions for edge case like `move horizontally flipped vertically` being resolved as the icon `move vertically` or `remove user add effect sepia` using the `add user` icon

I hope i answered your questions, you know where to find me
